In [1]:
import geopandas as gp

In [2]:
sf = gp.read_file('E:/Transit-Casa-Alex/Input/2010 Cenusus Shapefiles/2010 Census Blocks/075/tl_2010_06075_tabblock10.shp')

In [3]:
sm = gp.read_file('E:/Transit-Casa-Alex/Input/2010 Cenusus Shapefiles/2010 Census Blocks/081/tl_2010_06081_tabblock10.shp')

In [4]:
sm.head()

,ALAND10,AWATER10,BLOCKCE10,COUNTYFP10,FUNCSTAT10,GEOID10,INTPTLAT10,INTPTLON10,MTFCC10,NAME10,STATEFP10,TRACTCE10,UACE10,UATYP10,UR10,geometry
0,17681,0,4001,081,S,060816129004001,+37.4303914,-122.2008904,G5040,Block 4001,06,612900,78904,U,U,"POLYGON ((-122.20056 37.429328, -122.200823 37..."
1,24257,0,2006,081,S,060816128002006,+37.4343706,-122.2005754,G5040,Block 2006,06,612800,78904,U,U,"POLYGON ((-122.199776 37.433238, -122.199876 3..."
2,146005,0,2000,081,S,060816086002000,+37.5331810,-122.2714609,G5040,Block 2000,06,608600,78904,U,U,"POLYGON ((-122.271082 37.534214, -122.266892 3..."
3,38352,0,2006,081,S,060816113002006,+37.4527839,-122.2266250,G5040,Block 2006,06,611300,78904,U,U,"POLYGON ((-122.226065 37.451969, -122.226142 3..."
4,21309,0,2005,081,S,060816096032005,+37.4817289,-122.2801183,G5040,Block 2005,06,609603,78904,U,U,"POLYGON ((-122.279525 37.480797, -122.279894 3..."

In [5]:
sf.head()

,ALAND10,AWATER10,BLOCKCE10,COUNTYFP10,FUNCSTAT10,GEOID10,INTPTLAT10,INTPTLON10,MTFCC10,NAME10,STATEFP10,TRACTCE10,UACE10,UATYP10,UR10,geometry
0,16958,0,2002,075,S,060750213002002,+37.7500665,-122.4410751,G5040,Block 2002,06,021300,78904,U,U,"POLYGON ((-122.440616 37.750902, -122.440459 3..."
1,16823,0,2000,075,S,060750213002000,+37.7501958,-122.4389330,G5040,Block 2000,06,021300,78904,U,U,"POLYGON ((-122.438397 37.750226, -122.43832 37..."
2,17020,0,3004,075,S,060750205003004,+37.7567937,-122.4362701,G5040,Block 3004,06,020500,78904,U,U,"POLYGON ((-122.435808 37.757623, -122.435642 3..."
3,16415,0,1003,075,S,060750212001003,+37.7535291,-122.4370498,G5040,Block 1003,06,021200,78904,U,U,"POLYGON ((-122.436527 37.75354, -122.436454 37..."
4,17523,0,4001,075,S,060750211004001,+37.7557580,-122.4334002,G5040,Block 4001,06,021100,78904,U,U,"POLYGON ((-122.432331 37.756227, -122.432254 3..."