In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import statsmodels.api as smf

pd.set_option('display.max_columns', 500)


%matplotlib inline

In [83]:
diff = pd.read_csv('E:\Transit-Casa-Alex\Output/Modeling/2009/Diff_Mapping_Data.csv',index_col = 0)

In [84]:
diff.columns

Index(['LOG_RIDERS', 'EDD_EMP_LOG', 'STOP_ID', 'AVG_RIDE', 'FREQ_S_LOG',
       'EOL_SOL', 'HOUSING_09_DEN_LOG', 'SHR_INCOME_100P',
       'PARK_HOURLY_AVG_ON_LOG', 'ONTIME5', 'AVG_BART_LOG', 'CLOSE_STOP',
       'LIMITED', 'EXPRESS', 'TRANSBAY', 'MUNI_RAIL_AVG',
       'PRED_AVG_RIDERSHIP'],
      dtype='object')

In [85]:
diff.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 16733 entries, 0.0 to nan
Data columns (total 17 columns):
LOG_RIDERS                6261 non-null float64
EDD_EMP_LOG               6261 non-null float64
STOP_ID                   6261 non-null float64
AVG_RIDE                  6261 non-null float64
FREQ_S_LOG                6261 non-null float64
EOL_SOL                   6261 non-null float64
HOUSING_09_DEN_LOG        6261 non-null float64
SHR_INCOME_100P           6261 non-null float64
PARK_HOURLY_AVG_ON_LOG    6261 non-null float64
ONTIME5                   6261 non-null float64
AVG_BART_LOG              6261 non-null float64
CLOSE_STOP                6261 non-null float64
LIMITED                   6261 non-null float64
EXPRESS                   6261 non-null float64
TRANSBAY                  6261 non-null float64
MUNI_RAIL_AVG             6261 non-null float64
PRED_AVG_RIDERSHIP        6261 non-null float64
dtypes: float64(17)
memory usage: 2.3 MB

In [86]:
diff.columns

Index(['LOG_RIDERS', 'EDD_EMP_LOG', 'STOP_ID', 'AVG_RIDE', 'FREQ_S_LOG',
       'EOL_SOL', 'HOUSING_09_DEN_LOG', 'SHR_INCOME_100P',
       'PARK_HOURLY_AVG_ON_LOG', 'ONTIME5', 'AVG_BART_LOG', 'CLOSE_STOP',
       'LIMITED', 'EXPRESS', 'TRANSBAY', 'MUNI_RAIL_AVG',
       'PRED_AVG_RIDERSHIP'],
      dtype='object')

In [87]:
grouped = diff.groupby(by = 'STOP_ID',as_index = False).sum()

In [88]:
len(grouped)

3475

In [89]:
grouped.head()

,STOP_ID,LOG_RIDERS,EDD_EMP_LOG,AVG_RIDE,FREQ_S_LOG,EOL_SOL,HOUSING_09_DEN_LOG,SHR_INCOME_100P,PARK_HOURLY_AVG_ON_LOG,ONTIME5,AVG_BART_LOG,CLOSE_STOP,LIMITED,EXPRESS,TRANSBAY,MUNI_RAIL_AVG,PRED_AVG_RIDERSHIP
0,390.0,23.370079,41.805036,879.291269,6.781707,1.0,23.733903,0.326560,25.217126,3.190514,0.0,5.0,1.0,0.0,0.0,4130.0,265.899113
1,392.0,9.612275,6.993015,289.669267,3.131184,0.0,11.725666,0.439914,10.606610,1.307876,0.0,2.0,1.0,0.0,0.0,0.0,67.323363
2,660.0,1.111047,5.602119,2.037536,1.549089,0.0,5.712961,0.447944,5.303305,0.606256,0.0,1.0,0.0,0.0,0.0,0.0,33.390959
3,913.0,5.733169,4.394449,34.294630,2.473309,2.0,9.462831,0.110497,0.000000,1.028113,0.0,2.0,0.0,0.0,0.0,0.0,43.923873
4,3001.0,2.425865,8.767173,10.312014,1.746909,0.0,2.632486,0.537464,5.762051,0.706345,0.0,1.0,0.0,0.0,0.0,0.0,62.517901

In [90]:
grouped.head()

,STOP_ID,LOG_RIDERS,EDD_EMP_LOG,AVG_RIDE,FREQ_S_LOG,EOL_SOL,HOUSING_09_DEN_LOG,SHR_INCOME_100P,PARK_HOURLY_AVG_ON_LOG,ONTIME5,AVG_BART_LOG,CLOSE_STOP,LIMITED,EXPRESS,TRANSBAY,MUNI_RAIL_AVG,PRED_AVG_RIDERSHIP
0,390.0,23.370079,41.805036,879.291269,6.781707,1.0,23.733903,0.326560,25.217126,3.190514,0.0,5.0,1.0,0.0,0.0,4130.0,265.899113
1,392.0,9.612275,6.993015,289.669267,3.131184,0.0,11.725666,0.439914,10.606610,1.307876,0.0,2.0,1.0,0.0,0.0,0.0,67.323363
2,660.0,1.111047,5.602119,2.037536,1.549089,0.0,5.712961,0.447944,5.303305,0.606256,0.0,1.0,0.0,0.0,0.0,0.0,33.390959
3,913.0,5.733169,4.394449,34.294630,2.473309,2.0,9.462831,0.110497,0.000000,1.028113,0.0,2.0,0.0,0.0,0.0,0.0,43.923873
4,3001.0,2.425865,8.767173,10.312014,1.746909,0.0,2.632486,0.537464,5.762051,0.706345,0.0,1.0,0.0,0.0,0.0,0.0,62.517901

In [91]:
grouped['DIFF_AVG_RIDERSHIP'] = grouped.PRED_AVG_RIDERSHIP - grouped.AVG_RIDE
grouped['PDIFF_AVG_RIDERSHIP'] = (grouped.DIFF_AVG_RIDERSHIP/grouped.AVG_RIDE)*100

In [92]:
grouped.PDIFF_AVG_RIDERSHIP.mean()

inf

In [93]:
grouped.DIFF_AVG_RIDERSHIP.sum()

-147532.4633065544

In [94]:
grouped.DIFF_AVG_RIDERSHIP.mean()

-42.45538512418831

In [95]:
store = pd.HDFStore('E:\Transit-Casa-Alex\Input\Bus Performence/sfmuni_monthly_ts.h5')

In [19]:
store.items

<bound method HDFStore.items of <class 'pandas.io.pytables.HDFStore'>
File path: E:\Transit-Casa-Alex\Input\Bus Performence/sfmuni_monthly_ts.h5
/rs_day                          frame_table  (typ->appendable,nrows->543005,ncols->58,indexers->[index],dc->[MONTH,DOW,AGENCY_ID,ROUTE_SHORT_NAME,DIR,SEQ,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,IMP_TRIP_STOPS,WGT_TRIP_STOPS,STOP_ID,ROUTE_LONG_NAME,ROUTE_TYPE,TRIP_HEADSIGN,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS])
/rs_tod                          frame_table  (typ->appendable,nrows->2839604,ncols->59,indexers->[index],dc->[MONTH,DOW,TOD,AGENCY_ID,ROUTE_SHORT_NAME,DIR,SEQ,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,STOP_ID,ROUTE_LONG_NAME,ROUTE_TYPE,TRIP_HEADSIGN,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS,IMP_TRIP_STOPS])
/rs_tod_observed_only            frame_table  (typ->appendable,nrows->2839604,ncols->58,indexers->[index],dc->[MONTH,DOW,TOD,AGENCY_ID,ROUTE_SHORT_NAME,DIR,SEQ,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,STOP_ID,ROUTE_LONG_NAME,ROUTE_TYPE,TRIP_HEADSIGN,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS])
/stop_day                        frame_table  (typ->appendable,nrows->316767,ncols->52,indexers->[index],dc->[MONTH,DOW,AGENCY_ID,STOP_ID,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,IMP_TRIP_STOPS,WGT_TRIP_STOPS,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS])
/stop_tod                        frame_table  (typ->appendable,nrows->2015805,ncols->53,indexers->[index],dc->[MONTH,DOW,TOD,AGENCY_ID,STOP_ID,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,IMP_TRIP_STOPS,WGT_TRIP_STOPS,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS])                                                                  >

In [96]:
stops = store.select('stop_day',where = "'MONTH' == ['2009-10-01','2009-11-01','2009-12-01']")

In [97]:
#stops = pd.read_csv('E:/Transit-Casa-Alex/Input/Bus_Stops/2009/Post-Deleted_Stops/Bus_Stops.csv',index_col = 0)

In [98]:
stops.head()

,MONTH,DOW,AGENCY_ID,STOP_ID,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,IMP_TRIP_STOPS,WGT_TRIP_STOPS,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS
14252,2009-10-01,1,SFMTA,390,22,15.0,306,33,5.0,310.157179,21.963047,2.0,19TH AVENUE & HOLLOWAY ST,19TH AVE&HOLLOWAY AVE NE-,37.721190,-122.475096,0,0,1.0,1.095335,1.973266,0.0,142.199177,274.72,177.756764,274.72,319.955941,28.833,28.824349,6.30,9.73,6.30,5.41,0.623051,2115.839702,1547.149534,5495.925001,6064.615168,584.924534,122.440839,428.772542,4231.679404,8044.115721,6844.334599,1.635543,499.758808,0.0,0.000000,4522.683813,0.285072,0.030993,12.494407
14253,2009-10-01,1,SFMTA,392,22,16.0,121,12,0.0,120.956946,14.200601,2.0,19TH AVE & LINCOLN WAY,19TH AVE & LINCOLN WAY SE,37.765159,-122.477210,0,0,1.0,5.058116,5.399384,0.0,41.261999,85.30,83.548686,85.30,124.810685,14.520,14.514834,10.21,10.42,10.21,6.98,0.494422,389.210166,278.565285,3012.390062,3123.034944,361.486807,57.738747,36.770916,778.420332,2578.528531,2393.453910,0.000000,212.138890,0.0,1.502778,1489.868635,0.395279,0.032313,5.060007
14254,2009-10-01,1,SFMTA,660,22,14.0,134,7,0.0,144.551330,16.184811,2.0,MISSION ST & OCEAN AVENUE,MISSION ST&OCEAN AVE -MI/,37.723914,-122.435387,0,0,1.0,1.463682,1.463682,0.0,0.000000,36.44,86.887146,36.44,86.887146,3.752,4.041499,6.18,2.79,6.18,2.79,0.577752,2.710450,3.646218,1186.082602,1185.146835,33.210313,13.508054,0.169350,5.420900,9.621531,9.621531,1.021226,0.000000,0.0,0.000000,1346.389429,0.093580,0.000000,0.000000
14255,2009-10-01,1,SFMTA,913,22,7.0,91,8,2.0,93.872427,24.548077,2.0,DUBLIN ST & LAGRANDE AVE,DUBLIN ST&LAGRANDE AVE S - EOL,37.719192,-122.425802,1,0,1.0,6.274276,6.695619,0.0,0.000000,32.83,47.329485,32.83,47.329485,3.496,3.582448,6.39,4.54,6.39,4.54,0.412813,34.416044,61.433359,164.161462,137.144146,8.723907,1.579842,6.682208,68.832087,217.873917,200.179090,0.500000,70.533967,0.0,0.285714,2461.055769,0.028226,0.000000,0.000000
14256,2009-10-01,1,SFMTA,3001,22,15.0,63,7,0.0,63.000000,12.666667,2.0,1ST ST & HOWARD ST,1ST ST&HOWARD ST E-MB/SI,37.788530,-122.396044,0,0,1.0,1.562380,1.580456,0.0,1.141352,43.61,48.225618,43.61,49.366970,4.284,4.284000,5.89,5.33,5.89,5.21,0.718134,24.308095,7.778571,1105.478802,1122.008325,75.172559,15.932149,2.193611,48.616190,61.581029,57.512162,0.000000,7.322381,0.0,0.000000,926.250000,0.278528,0.000000,0.000000

In [99]:
stops.columns

Index(['MONTH', 'DOW', 'AGENCY_ID', 'STOP_ID', 'NUMDAYS', 'OBSDAYS',
       'TRIP_STOPS', 'OBS_TRIP_STOPS', 'IMP_TRIP_STOPS', 'WGT_TRIP_STOPS',
       'HEADWAY_S', 'FARE', 'STOPNAME', 'STOPNAME_AVL', 'STOP_LAT', 'STOP_LON',
       'EOL', 'SOL', 'TIMEPOINT', 'ARRIVAL_TIME_DEV', 'DEPARTURE_TIME_DEV',
       'DWELL_S', 'DWELL', 'RUNTIME_S', 'RUNTIME', 'TOTTIME_S', 'TOTTIME',
       'SERVMILES_S', 'SERVMILES', 'RUNSPEED_S', 'RUNSPEED', 'TOTSPEED_S',
       'TOTSPEED', 'ONTIME5', 'ON', 'OFF', 'LOAD_ARR', 'LOAD_DEP', 'PASSMILES',
       'PASSHOURS', 'WAITHOURS', 'FULLFARE_REV', 'PASSDELAY_DEP',
       'PASSDELAY_ARR', 'RDBRDNGS', 'DOORCYCLES', 'WHEELCHAIR', 'BIKERACK',
       'CAPACITY', 'VC', 'CROWDED', 'CROWDHOURS'],
      dtype='object')

In [100]:
agg = {'STOPNAME':'first', 'STOP_LAT':'mean','STOP_LON':'mean'}

In [101]:
grouped_stops = stops.groupby(by = 'STOP_ID',as_index = False).agg(agg)

In [102]:
merged = pd.merge(grouped_stops,grouped, how = 'inner', on = 'STOP_ID')

In [103]:
merged.head()

,STOP_ID,STOPNAME,STOP_LAT,STOP_LON,LOG_RIDERS,EDD_EMP_LOG,AVG_RIDE,FREQ_S_LOG,EOL_SOL,HOUSING_09_DEN_LOG,SHR_INCOME_100P,PARK_HOURLY_AVG_ON_LOG,ONTIME5,AVG_BART_LOG,CLOSE_STOP,LIMITED,EXPRESS,TRANSBAY,MUNI_RAIL_AVG,PRED_AVG_RIDERSHIP,DIFF_AVG_RIDERSHIP,PDIFF_AVG_RIDERSHIP
0,390,19TH AVENUE & HOLLOWAY ST,37.721190,-122.475096,23.370079,41.805036,879.291269,6.781707,1.0,23.733903,0.326560,25.217126,3.190514,0.0,5.0,1.0,0.0,0.0,4130.0,265.899113,-613.392156,-69.759837
1,392,19TH AVE & LINCOLN WAY,37.765159,-122.477210,9.612275,6.993015,289.669267,3.131184,0.0,11.725666,0.439914,10.606610,1.307876,0.0,2.0,1.0,0.0,0.0,0.0,67.323363,-222.345904,-76.758541
2,660,MISSION ST & OCEAN AVENUE,37.723914,-122.435387,1.111047,5.602119,2.037536,1.549089,0.0,5.712961,0.447944,5.303305,0.606256,0.0,1.0,0.0,0.0,0.0,0.0,33.390959,31.353424,1538.791254
3,913,DUBLIN ST & LAGRANDE AVE,37.719192,-122.425802,5.733169,4.394449,34.294630,2.473309,2.0,9.462831,0.110497,0.000000,1.028113,0.0,2.0,0.0,0.0,0.0,0.0,43.923873,9.629243,28.077990
4,3001,1ST ST & HOWARD ST,37.788530,-122.396044,2.425865,8.767173,10.312014,1.746909,0.0,2.632486,0.537464,5.762051,0.706345,0.0,1.0,0.0,0.0,0.0,0.0,62.517901,52.205887,506.262774

In [104]:
len(merged)
merged.head()

,STOP_ID,STOPNAME,STOP_LAT,STOP_LON,LOG_RIDERS,EDD_EMP_LOG,AVG_RIDE,FREQ_S_LOG,EOL_SOL,HOUSING_09_DEN_LOG,SHR_INCOME_100P,PARK_HOURLY_AVG_ON_LOG,ONTIME5,AVG_BART_LOG,CLOSE_STOP,LIMITED,EXPRESS,TRANSBAY,MUNI_RAIL_AVG,PRED_AVG_RIDERSHIP,DIFF_AVG_RIDERSHIP,PDIFF_AVG_RIDERSHIP
0,390,19TH AVENUE & HOLLOWAY ST,37.721190,-122.475096,23.370079,41.805036,879.291269,6.781707,1.0,23.733903,0.326560,25.217126,3.190514,0.0,5.0,1.0,0.0,0.0,4130.0,265.899113,-613.392156,-69.759837
1,392,19TH AVE & LINCOLN WAY,37.765159,-122.477210,9.612275,6.993015,289.669267,3.131184,0.0,11.725666,0.439914,10.606610,1.307876,0.0,2.0,1.0,0.0,0.0,0.0,67.323363,-222.345904,-76.758541
2,660,MISSION ST & OCEAN AVENUE,37.723914,-122.435387,1.111047,5.602119,2.037536,1.549089,0.0,5.712961,0.447944,5.303305,0.606256,0.0,1.0,0.0,0.0,0.0,0.0,33.390959,31.353424,1538.791254
3,913,DUBLIN ST & LAGRANDE AVE,37.719192,-122.425802,5.733169,4.394449,34.294630,2.473309,2.0,9.462831,0.110497,0.000000,1.028113,0.0,2.0,0.0,0.0,0.0,0.0,43.923873,9.629243,28.077990
4,3001,1ST ST & HOWARD ST,37.788530,-122.396044,2.425865,8.767173,10.312014,1.746909,0.0,2.632486,0.537464,5.762051,0.706345,0.0,1.0,0.0,0.0,0.0,0.0,62.517901,52.205887,506.262774

In [106]:
merged.to_csv('E:/Transit-Casa-Alex/Output/Modeling/2009/Diff_Mapping_Data.csv')

# Try to make the mod 2016 -mod 2009 diff map

In [43]:
df = pd.read_csv('E:/Transit-Casa-Alex/Output/Modeling/2016/Diff_Mapping_Data.csv',thousands = ',',index_col = 0)

In [44]:
df

,LOG_RIDERS,EDD_EMP_LOG,STOP_ID,AVG_RIDE,FREQ_S_LOG,EOL_SOL,HOUSING_16_DEN_LOG,SHR_INCOME_100P,PARK_HOURLY_AVG_ON_LOG,ONTIME5,AVG_BART_LOG,CLOSE_STOP,LIMITED,EXPRESS,TRANSBAY,MUNI_RAIL_AVG,PRED_AVG_RIDERSHIP
0,6.477286,4.442651,390,649.203572,1.790344,0.0,4.746781,0.697574,5.043425,0.783766,0.000000,1,0,0,0,2660.15,50.625766
1,5.699720,4.442651,390,297.783774,1.944524,0.0,4.746781,0.697574,5.043425,0.577916,0.000000,0,1,0,0,2660.15,77.314856
2,3.784672,4.442651,390,43.021243,1.790290,0.0,4.746781,0.697574,5.043425,0.277249,0.000000,1,0,0,0,2660.15,38.114825
3,2.852759,4.442651,390,16.335544,1.098612,1.0,4.746781,0.697574,5.043425,0.722235,0.000000,1,0,0,0,2660.15,13.537710
4,2.781043,4.406719,913,15.135847,1.211610,1.0,4.731255,0.208029,0.000000,0.599620,0.000000,1,0,0,0,0.00,23.928277
5,2.552064,4.406719,913,11.833570,1.203783,1.0,4.731255,0.208029,0.000000,0.619248,0.000000,1,0,0,0,0.00,23.644524
6,4.177217,8.191740,3003,64.184177,1.540978,0.0,6.014714,0.651526,5.726848,0.541655,0.000000,1,0,0,0,0.00,36.167947
7,4.390278,8.377011,3004,79.662853,1.530538,0.0,5.930357,0.651526,5.560682,0.578665,0.000000,1,0,0,0,0.00,36.267822
8,4.378818,8.851520,3008,78.743698,1.530227,0.0,5.930843,0.651526,5.993961,0.646308,0.000000,1,0,0,0,0.00,40.587240
9,4.159577,8.851520,3008,63.044457,1.497576,0.0,5.930843,0.651526,5.993961,0.559290,0.000000,1,0,0,0,0.00,35.145300
10,3.997431,8.449343,3009,53.458049,1.540944,0.0,6.038455,0.651526,5.932245,0.517151,0.000000,0,0,0,0,0.00,138.271376
11,3.997901,8.476788,3010,53.483642,1.530338,0.0,5.991045,0.651526,5.147494,0.639638,0.000000,1,0,0,0,0.00,37.906347
12,4.707944,8.586159,3011,109.824074,1.530102,0.0,6.042849,0.651526,5.652489,0.662271,0.000000,1,0,0,0,0.00,39.635413
13,4.041595,8.586159,3011,55.917041,1.497477,0.0,6.042849,0.651526,5.652489,0.593524,0.000000,1,0,0,0,0.00,34.675791
14,5.442587,9.755162,3013,230.039197,1.529895,0.0,4.497603,0.651526,4.634729,0.700913,9.091951,1,0,0,1,9163.45,301.410002
15,4.907553,9.755162,3013,134.307945,1.497311,0.0,4.497603,0.651526,4.634729,0.649677,9.091951,1,0,0,1,9163.45,267.089766
16,3.623294,7.481556,3015,36.460774,1.530648,0.0,6.305118,0.651526,5.765191,0.550512,0.000000,1,0,0,0,2728.00,40.651599
17,0.602454,3.218876,3016,0.826596,1.098568,0.0,6.487450,0.518356,4.836282,0.749149,0.000000,1,0,0,0,496.05,6.693249
18,5.272419,5.774552,3018,193.886879,1.339172,0.0,5.201811,0.272411,5.303305,0.602681,0.000000,1,0,0,0,0.00,21.800055
19,5.787248,5.808142,3019,325.114175,1.353934,0.0,5.223758,0.272411,5.303305,0.576697,0.000000,1,0,0,0,0.00,22.598990
20,3.004250,4.369448,3020,19.171080,1.339379,0.0,5.071783,0.272411,0.000000,0.631924,0.000000,1,0,0,0,0.00,15.764485
21,2.810622,4.477337,3021,15.620249,1.339772,0.0,5.127726,0.272411,0.000000,0.537044,0.000000,1,0,0,0,0.00,15.260744
23,3.367422,4.744932,3024,28.003663,1.648390,0.0,6.175879,0.576243,0.000000,0.644940,0.000000,1,0,0,0,0.00,31.905470
24,3.520925,4.744932,3024,32.815686,1.816698,0.0,6.175879,0.576243,0.000000,0.541143,0.000000,1,0,0,0,0.00,49.104198
29,3.825234,6.878326,3031,44.843519,1.888570,0.0,6.524083,0.355295,0.000000,0.217410,0.000000,1,0,0,0,0.00,92.315658
30,3.148124,6.878326,3031,22.292328,2.222526,0.0,6.524083,0.355295,0.000000,0.353033,0.000000,1,0,1,0,0.00,37.333409
31,4.005013,5.023881,3032,53.872528,1.681235,0.0,6.222336,0.346882,5.303305,0.515596,0.000000,1,0,0,0,0.00,51.688833
32,2.603133,5.023881,3032,12.505991,1.620130,0.0,6.222336,0.346882,5.303305,0.331842,0.000000,1,0,1,0,0.00,4.926853
33,4.049937,5.257495,3033,56.393833,1.292494,0.0,6.226513,0.346882,5.303305,0.695618,0.000000,1,0,0,0,0.00,18.930060
34,2.968990,5.257495,3033,18.472236,1.865572,0.0,6.226513,0.346882,5.303305,0.763311,0.000000,1,0,1,0,0.00,14.541108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5548,2.105149,5.793014,7841,7.208323,1.102882,0.0,5.979705,0.489922,5.303305,0.420151,0.000000,0,0,0,0,0.00,9.377831
5549,2.255066,5.793014,7841,8.535919,1.970510,0.0,5.979705,0.489922,5.303305,0.416452,0.000000,0,0,0,0,0.00,175.245041
5552,2.257619,3.295837,7843,8.560298,1.320129,0.0,5.475326,0.509495,0.000000,0.575728,0.000000,1,0,0,0,0.00,7.308189
5553,5.398950,5.707110,7844,220.174121,2.070873,0.0,6.080040,0.436496,5.303305,0.765845,0.000000,1,0,0,0,0.00,27.752874
5554,4.292048,5.899897,7845,72.116042,1.204202,0.0,5.192123,0.760369,0.000000,0.755467,0.000000,1,0,0,0,0.00,26.338025
5555,3.714116,5.888878,7846,40.022305,1.204202,0.0,4.654307,0.760369,0.000000,0.768182,0.000000,0,0,0,0,0.00,19.914170
5556,3.442138,4.330733,7847,30.253711,1.204202,0.0,4.032215,0.581275,0.000000,0.771836,0.000000,0,0,0,0,0.00,14.490862
5557,4.749214,5.164786,7848,114.493439,1.521104,0.0,5.143791,0.581275,0.000000,0.584383,0.000000,1,0,0,0,0.00,45.086844
5558,1.870401,2.890372,7849,5.490901,1.521089,0.0,5.512820,0.581275,0.000000,0.520440,0.000000,1,0,0,0,0.00,25.426846
5559,1.375346,2.079442,7851,2.956444,1.360472,0.0,3.960572,0.202381,0.000000,0.623764,0.000000,0,0,0,0,0.00,35.967922
5560,1.665799,2.079442,7852,4.289898,1.341964,0.0,4.035816,0.582440,0.000000,0.548095,0.000000,0,0,0,0,0.00,89.096585
5561,3.660660,4.248495,7853,37.886985,1.778807,0.0,5.072692,0.499376,0.000000,0.342422,0.000000,1,0,0,0,0.00,6.129057
5562,5.630196,6.862758,7854,277.716657,1.348342,0.0,5.979612,0.346882,5.303305,0.456249,0.000000,0,0,0,0,0.00,213.558348
5563,2.921278,6.862758,7854,17.565000,1.622180,0.0,5.979612,0.346882,5.303305,0.256325,0.000000,1,0,1,0,0.00,40.793705
5564,6.325617,6.862758,7854,557.702299,2.508257,0.0,5.979612,0.346882,5.303305,0.587180,0.000000,1,1,0,0,0.00,36.717358
5565,4.359476,5.365976,7856,77.216121,1.726452,0.0,6.569523,0.650373,0.000000,0.617246,0.000000,1,0,0,0,0.00,48.485595
5566,4.239853,5.365976,7856,68.397677,2.398932,0.0,6.569523,0.650373,0.000000,0.436986,0.000000,1,0,1,0,0.00,7.346977
5567,4.163580,5.220356,7857,63.301340,1.808572,0.0,6.568379,0.650373,0.000000,0.536243,0.000000,1,0,0,0,0.00,186.432887
5568,2.963349,5.220356,7857,18.362705,1.882671,0.0,6.568379,0.650373,0.000000,0.392126,0.000000,1,0,1,0,0.00,14.609297
5569,4.634138,7.259820,7858,101.939155,1.808972,0.0,7.107654,0.008363,5.707110,0.673052,0.000000,1,0,0,0,0.00,67.308477
5570,4.052298,1.098612,7860,56.529483,1.515403,0.0,5.058331,0.335366,0.000000,0.533366,0.000000,1,0,0,0,0.00,60.857520
5571,4.499139,8.173293,7862,88.939635,1.529180,0.0,6.141999,0.230235,5.620401,0.746825,0.000000,1,0,0,0,0.00,83.463714
5572,4.330761,8.173293,7862,75.002086,1.497113,0.0,6.141999,0.230235,5.620401,0.731735,0.000000,1,0,0,0,0.00,75.103496
5573,4.018171,8.682877,7863,54.599341,1.529290,0.0,5.332120,0.041257,5.877736,0.727902,0.000000,1,0,0,0,0.00,11.731624
5574,3.881619,8.682877,7863,47.502680,1.497067,0.0,5.332120,0.041257,5.877736,0.704444,0.000000,1,0,0,0,0.00,20.865662
5575,3.392554,4.158883,7864,28.741807,1.506435,0.0,0.000000,0.390212,0.000000,0.559860,0.000000,1,0,0,0,0.00,14.504273
5576,3.187128,5.786897,7865,23.218772,1.561131,0.0,1.212597,0.518356,4.836282,0.718386,0.000000,1,0,0,0,0.00,8.992502
5577,3.903348,5.786897,7866,48.568125,1.564880,0.0,1.750373,0.760369,4.836282,0.514170,0.000000,1,0,0,0,0.00,8.105330
5578,1.449419,3.091042,7867,3.260639,1.320129,0.0,5.669736,0.588865,0.000000,0.698450,0.000000,1,0,0,0,0.00,8.105330
5579,1.607743,2.890372,7868,3.991532,1.320129,0.0,5.675129,0.588865,0.000000,0.576618,0.000000,1,0,0,0,0.00,8.105330

In [45]:
df.head()

,LOG_RIDERS,EDD_EMP_LOG,STOP_ID,AVG_RIDE,FREQ_S_LOG,EOL_SOL,HOUSING_16_DEN_LOG,SHR_INCOME_100P,PARK_HOURLY_AVG_ON_LOG,ONTIME5,AVG_BART_LOG,CLOSE_STOP,LIMITED,EXPRESS,TRANSBAY,MUNI_RAIL_AVG,PRED_AVG_RIDERSHIP
0,6.477286,4.442651,390,649.203572,1.790344,0.0,4.746781,0.697574,5.043425,0.783766,0.0,1,0,0,0,2660.15,50.625766
1,5.699720,4.442651,390,297.783774,1.944524,0.0,4.746781,0.697574,5.043425,0.577916,0.0,0,1,0,0,2660.15,77.314856
2,3.784672,4.442651,390,43.021243,1.790290,0.0,4.746781,0.697574,5.043425,0.277249,0.0,1,0,0,0,2660.15,38.114825
3,2.852759,4.442651,390,16.335544,1.098612,1.0,4.746781,0.697574,5.043425,0.722235,0.0,1,0,0,0,2660.15,13.537710
4,2.781043,4.406719,913,15.135847,1.211610,1.0,4.731255,0.208029,0.000000,0.599620,0.0,1,0,0,0,0.00,23.928277

In [46]:
len(df)

5254

In [50]:
grouped16 = df.groupby(by = 'STOP_ID',as_index = False).sum()

In [62]:
grouped16['DIFF_AVG_RIDERSHIP'] = grouped16.PRED_AVG_RIDERSHIP - grouped16.AVG_RIDE
grouped16['PDIFF_AVG_RIDERSHIP'] = (grouped16.DIFF_AVG_RIDERSHIP/grouped16.AVG_RIDE)*100

In [63]:
grouped_stops = stops.groupby(by = 'STOP_ID',as_index = False).agg(agg)

In [69]:
store = pd.HDFStore('E:\Transit-Casa-Alex\Input\Bus Performence/sfmuni_monthly_ts.h5')

stops16 = store.select('stop_day',where = "'MONTH' == ['2016-10-01','2016-11-01','2016-12-01']")

grouped_stops16 = stops16.groupby(by = 'STOP_ID',as_index = False).agg(agg)

In [70]:
merged = pd.merge(grouped_stops16,grouped16, how = 'inner', on = 'STOP_ID')

In [71]:
merged.head()

,STOP_ID,STOPNAME,STOP_LAT,STOP_LON,LOG_RIDERS,EDD_EMP_LOG,AVG_RIDE,FREQ_S_LOG,EOL_SOL,HOUSING_16_DEN_LOG,SHR_INCOME_100P,PARK_HOURLY_AVG_ON_LOG,ONTIME5,AVG_BART_LOG,CLOSE_STOP,LIMITED,EXPRESS,TRANSBAY,MUNI_RAIL_AVG,PRED_AVG_RIDERSHIP,DIFF_AVG_RIDERSHIP,PDIFF_AVG_RIDERSHIP
0,390,19TH AVENUE & HOLLOWAY ST,37.721190,-122.475096,18.814437,17.770605,1006.344132,6.623770,1.0,18.987122,2.790295,20.173700,2.361166,0.0,3,1,0,0,10640.6,179.593158,-826.750974,-82.153902
1,913,DUBLIN ST & LAGRANDE AVE,37.719192,-122.425802,5.333108,8.813438,26.969417,2.415393,2.0,9.462510,0.416058,0.000000,1.218868,0.0,2,0,0,0,0.0,47.572800,20.603383,76.395360
2,3003,2ND ST & BRANNAN ST,37.781827,-122.391945,4.177217,8.191740,64.184177,1.540978,0.0,6.014714,0.651526,5.726848,0.541655,0.0,1,0,0,0,0.0,36.167947,-28.016229,-43.649745
3,3004,2ND ST & BRANNAN ST,37.781854,-122.392232,4.390278,8.377011,79.662853,1.530538,0.0,5.930357,0.651526,5.560682,0.578665,0.0,1,0,0,0,0.0,36.267822,-43.395031,-54.473357
4,3008,2ND ST & FOLSOM ST,37.785318,-122.396562,8.538395,17.703041,141.788155,3.027804,0.0,11.861686,1.303051,11.987923,1.205598,0.0,2,0,0,0,0.0,75.732540,-66.055615,-46.587541

In [72]:
len(merged)

3172

In [73]:
merged.columns

Index(['STOP_ID', 'STOPNAME', 'STOP_LAT', 'STOP_LON', 'LOG_RIDERS',
       'EDD_EMP_LOG', 'AVG_RIDE', 'FREQ_S_LOG', 'EOL_SOL',
       'HOUSING_16_DEN_LOG', 'SHR_INCOME_100P', 'PARK_HOURLY_AVG_ON_LOG',
       'ONTIME5', 'AVG_BART_LOG', 'CLOSE_STOP', 'LIMITED', 'EXPRESS',
       'TRANSBAY', 'MUNI_RAIL_AVG', 'PRED_AVG_RIDERSHIP', 'DIFF_AVG_RIDERSHIP',
       'PDIFF_AVG_RIDERSHIP'],
      dtype='object')

5.0248063660574207

In [81]:
merged.head()

,STOP_ID,STOPNAME,STOP_LAT,STOP_LON,LOG_RIDERS,EDD_EMP_LOG,AVG_RIDE,FREQ_S_LOG,EOL_SOL,HOUSING_16_DEN_LOG,SHR_INCOME_100P,PARK_HOURLY_AVG_ON_LOG,ONTIME5,AVG_BART_LOG,CLOSE_STOP,LIMITED,EXPRESS,TRANSBAY,MUNI_RAIL_AVG,PRED_AVG_RIDERSHIP,DIFF_AVG_RIDERSHIP,PDIFF_AVG_RIDERSHIP
0,390,19TH AVENUE & HOLLOWAY ST,37.721190,-122.475096,18.814437,17.770605,1006.344132,6.623770,1.0,18.987122,2.790295,20.173700,2.361166,0.0,3,1,0,0,10640.6,179.593158,-826.750974,-82.153902
1,913,DUBLIN ST & LAGRANDE AVE,37.719192,-122.425802,5.333108,8.813438,26.969417,2.415393,2.0,9.462510,0.416058,0.000000,1.218868,0.0,2,0,0,0,0.0,47.572800,20.603383,76.395360
2,3003,2ND ST & BRANNAN ST,37.781827,-122.391945,4.177217,8.191740,64.184177,1.540978,0.0,6.014714,0.651526,5.726848,0.541655,0.0,1,0,0,0,0.0,36.167947,-28.016229,-43.649745
3,3004,2ND ST & BRANNAN ST,37.781854,-122.392232,4.390278,8.377011,79.662853,1.530538,0.0,5.930357,0.651526,5.560682,0.578665,0.0,1,0,0,0,0.0,36.267822,-43.395031,-54.473357
4,3008,2ND ST & FOLSOM ST,37.785318,-122.396562,8.538395,17.703041,141.788155,3.027804,0.0,11.861686,1.303051,11.987923,1.205598,0.0,2,0,0,0,0.0,75.732540,-66.055615,-46.587541

In [75]:
merged.DIFF_AVG_RIDERSHIP.mean()

-1.0573449901557512

In [76]:
merged.DIFF_AVG_RIDERSHIP.sum()

-3353.8983087740426

In [78]:
merged.head()

,STOP_ID,STOPNAME,STOP_LAT,STOP_LON,LOG_RIDERS,EDD_EMP_LOG,AVG_RIDE,FREQ_S_LOG,EOL_SOL,HOUSING_16_DEN_LOG,SHR_INCOME_100P,PARK_HOURLY_AVG_ON_LOG,ONTIME5,AVG_BART_LOG,CLOSE_STOP,LIMITED,EXPRESS,TRANSBAY,MUNI_RAIL_AVG,PRED_AVG_RIDERSHIP,DIFF_AVG_RIDERSHIP,PDIFF_AVG_RIDERSHIP
0,390,19TH AVENUE & HOLLOWAY ST,37.721190,-122.475096,18.814437,17.770605,1006.344132,6.623770,1.0,18.987122,2.790295,20.173700,2.361166,0.0,3,1,0,0,10640.6,179.593158,-826.750974,-82.153902
1,913,DUBLIN ST & LAGRANDE AVE,37.719192,-122.425802,5.333108,8.813438,26.969417,2.415393,2.0,9.462510,0.416058,0.000000,1.218868,0.0,2,0,0,0,0.0,47.572800,20.603383,76.395360
2,3003,2ND ST & BRANNAN ST,37.781827,-122.391945,4.177217,8.191740,64.184177,1.540978,0.0,6.014714,0.651526,5.726848,0.541655,0.0,1,0,0,0,0.0,36.167947,-28.016229,-43.649745
3,3004,2ND ST & BRANNAN ST,37.781854,-122.392232,4.390278,8.377011,79.662853,1.530538,0.0,5.930357,0.651526,5.560682,0.578665,0.0,1,0,0,0,0.0,36.267822,-43.395031,-54.473357
4,3008,2ND ST & FOLSOM ST,37.785318,-122.396562,8.538395,17.703041,141.788155,3.027804,0.0,11.861686,1.303051,11.987923,1.205598,0.0,2,0,0,0,0.0,75.732540,-66.055615,-46.587541

In [79]:
len(merged)

3172

In [82]:
merged.to_csv('E:/Transit-Casa-Alex/Output/Modeling/2016/Diff_Mapping_Data.csv')