In [7]:
store.items

<bound method HDFStore.items of <class 'pandas.io.pytables.HDFStore'>
File path: E:/Transit_Casa/Output/sfmuni_monthly_ts.h5
/rs_day                  frame_table  (typ->appendable,nrows->301137,ncols->57,indexers->[index],dc->[MONTH,DOW,AGENCY_ID,ROUTE_SHORT_NAME,DIR,SEQ,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,STOP_ID,ROUTE_LONG_NAME,ROUTE_TYPE,TRIP_HEADSIGN,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS])
/rs_tod                  frame_table  (typ->appendable,nrows->1565864,ncols->58,indexers->[index],dc->[MONTH,DOW,TOD,AGENCY_ID,ROUTE_SHORT_NAME,DIR,SEQ,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,STOP_ID,ROUTE_LONG_NAME,ROUTE_TYPE,TRIP_HEADSIGN,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS])
/stop_day                frame_table  (typ->appendable,nrows->177415,ncols->51,indexers->[index],dc->[MONTH,DOW,AGENCY_ID,STOP_ID,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS])
/stop_tod                frame_table  (typ->appendable,nrows->1125515,ncols->52,indexers->[index],dc->[MONTH,DOW,TOD,AGENCY_ID,STOP_ID,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS])
/system_day_s            frame_table  (typ->appendable,nrows->53,ncols->38,indexers->[index],dc->[MONTH,DOW,AGENCY_ID,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,HEADWAY_S,FARE,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,VC,CROWDED,CROWDHOURS])
/system_tod_s            frame_table  (typ->appendable,nrows->371,ncols->39,indexers->[index],dc->[MONTH,DOW,TOD,AGENCY_ID,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,HEADWAY_S,FARE,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,VC,CROWDED,CROWDHOURS])                                                                                                                                                                                                       >

In [2]:
import csv as csv
import pandas as pd
import numpy as np
import folium
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [8]:
hdffile = "E:/Transit_Casa/Output/sfmuni_monthly_ts.h5"
store = pd.HDFStore(hdffile)
df = store.get('stop_day')
store.select?

In [81]:
mapa = folium.Map([37.775, -122.4813333],
                  zoom_start=10,
                  tiles='cartodbpositron')

In [82]:
df1 = df[df['MONTH'] == '2009-09-01']
df2 = df[df['MONTH'] == '2013-09-01']

In [83]:
df_final = pd.merge(df1,df2, how = 'outer', on = ['DOW', 'AGENCY_ID', 'STOP_ID'], suffixes = ['_09','_13'])

In [84]:
df_final = df_final.reindex_axis(sorted(df_final.columns), axis=1)

In [85]:
df_final['ON_DIFF'] = df_final['ON_13'] - df_final['ON_09']
df_final['ON_P_DIFF(FLOAT)'] = (df_final['ON_13'] - df_final['ON_09'])/df_final['ON_09']
df_final['ON_P_DIFF'] = ((df_final['ON_13'] - df_final['ON_09'])/df_final['ON_09'])*100

In [90]:
np.percentile(df_final['ON_09'].dropna(),5)

0.70465099170981516

In [8]:
df_final['ON_P_DIFF'] = df_final.ON_P_DIFF.astype(str) + '%'

In [9]:
df_final.head()

,AGENCY_ID,ARRIVAL_TIME_DEV_09,ARRIVAL_TIME_DEV_13,BIKERACK_09,BIKERACK_13,CAPACITY_09,CAPACITY_13,CROWDED_09,CROWDED_13,CROWDHOURS_09,...,VC_13,WAITHOURS_09,WAITHOURS_13,WGT_TRIP_STOPS_09,WGT_TRIP_STOPS_13,WHEELCHAIR_09,WHEELCHAIR_13,ON_DIFF,ON_P_DIFF(FLOAT),ON_P_DIFF
0,SFMTA,0.934607,1.757239,0.219167,1.592472,2877.954545,2560.95,0.060312,0.037341,21.520189,...,0.264026,377.780377,393.842721,273.297197,265.943718,0.000000,0.566667,-213.317617,-0.094988,-9.49876029208%
1,SFMTA,3.542134,NaN,0.399840,NaN,1093.909091,NaN,0.031747,NaN,4.584047,...,NaN,40.855085,NaN,119.847627,NaN,0.126824,NaN,NaN,NaN,nan%
2,SFMTA,1.770704,-0.344797,0.000000,0.000000,1505.818182,1242.70,0.000000,0.000000,0.000000,...,0.088846,0.147314,0.228783,135.850975,101.784411,0.000000,0.000000,0.178389,0.083941,8.3941360784%
3,SFMTA,4.582892,2.994147,0.226340,0.133333,1437.882353,1562.40,0.000000,0.000000,0.000000,...,0.041083,7.528386,2.838759,87.038251,79.000000,0.000000,0.000000,-29.414361,-0.681573,-68.1572790684%
4,SFMTA,2.883022,NaN,0.150224,NaN,804.681818,NaN,0.012185,NaN,0.929952,...,NaN,1.027610,NaN,63.000000,NaN,0.286364,NaN,NaN,NaN,nan%

In [37]:
for col in df_final.columns:
        print(col)

AGENCY_ID
ARRIVAL_TIME_DEV_09
ARRIVAL_TIME_DEV_13
BIKERACK_09
BIKERACK_13
CAPACITY_09
CAPACITY_13
CROWDED_09
CROWDED_13
CROWDHOURS_09
CROWDHOURS_13
DEPARTURE_TIME_DEV_09
DEPARTURE_TIME_DEV_13
DOORCYCLES_09
DOORCYCLES_13
DOW
DWELL_09
DWELL_13
DWELL_S_09
DWELL_S_13
EOL_09
EOL_13
FARE_09
FARE_13
FULLFARE_REV_09
FULLFARE_REV_13
HEADWAY_S_09
HEADWAY_S_13
LOAD_ARR_09
LOAD_ARR_13
LOAD_DEP_09
LOAD_DEP_13
MONTH_09
MONTH_13
NUMDAYS_09
NUMDAYS_13
OBSDAYS_09
OBSDAYS_13
OBS_TRIP_STOPS_09
OBS_TRIP_STOPS_13
OFF_09
OFF_13
ONTIME5_09
ONTIME5_13
ON_09
ON_13
PASSDELAY_ARR_09
PASSDELAY_ARR_13
PASSDELAY_DEP_09
PASSDELAY_DEP_13
PASSHOURS_09
PASSHOURS_13
PASSMILES_09
PASSMILES_13
RDBRDNGS_09
RDBRDNGS_13
RUNSPEED_09
RUNSPEED_13
RUNSPEED_S_09
RUNSPEED_S_13
RUNTIME_09
RUNTIME_13
RUNTIME_S_09
RUNTIME_S_13
SERVMILES_09
SERVMILES_13
SERVMILES_S_09
SERVMILES_S_13
SOL_09
SOL_13
STOPNAME_09
STOPNAME_13
STOPNAME_AVL_09
STOPNAME_AVL_13
STOP_ID
STOP_LAT_09
STOP_LAT_13
STOP_LON_09
STOP_LON_13
TIMEPOINT_09
TIMEPOINT_13
TOTSPEED_09
TOTSPEED_13
TOTSPEED_S_09
TOTSPEED_S_13
TOTTIME_09
TOTTIME_13
TOTTIME_S_09
TOTTIME_S_13
TRIP_STOPS_09
TRIP_STOPS_13
VC_09
VC_13
WAITHOURS_09
WAITHOURS_13
WGT_TRIP_STOPS_09
WGT_TRIP_STOPS_13
WHEELCHAIR_09
WHEELCHAIR_13
ON_DIFF
ON_P_DIFF(FLOAT)
ON_P_DIFF

In [100]:
df_final['HEADWAY_S_09'][0]

21.795986622073585

In [74]:
df = df_final[df_final['ON_09']== 0] 
df2 = df_final[df_final['ON_13']== 0] 
df3 = pd.merge(df,df2,how = 'left', on = 'STOP_ID')

,AGENCY_ID_x,ARRIVAL_TIME_DEV_09_x,ARRIVAL_TIME_DEV_13_x,BIKERACK_09_x,BIKERACK_13_x,CAPACITY_09_x,CAPACITY_13_x,CROWDED_09_x,CROWDED_13_x,CROWDHOURS_09_x,...,VC_13_y,WAITHOURS_09_y,WAITHOURS_13_y,WGT_TRIP_STOPS_09_y,WGT_TRIP_STOPS_13_y,WHEELCHAIR_09_y,WHEELCHAIR_13_y,ON_DIFF_y,ON_P_DIFF(FLOAT)_y,ON_P_DIFF_y
0,SFMTA,3.553991,7.193900,0.214258,0.000000,140.00,144.90,0.0,0.0,0.0,...,0.223347,0.0,0.0,9.672307,9.960352,0.0,0.0,0.0,NaN,nan%
1,SFMTA,0.078875,1.584359,0.000000,0.286783,324.45,1820.70,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SFMTA,3.704306,NaN,0.000000,NaN,136.50,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SFMTA,-0.739032,1.544508,0.000000,0.000000,324.45,283.50,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SFMTA,4.540167,8.065517,0.000000,0.000000,140.00,141.75,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df3 = pd.merge

In [58]:
-0.333 <= -0.333 <0.5555

True

In [28]:
np.isnan(df_final.ON_DIFF[1] )

True

In [24]:
df_final.ON_DIFF[1]

nan

In [11]:
from folium.element import IFrame
from folium.plugins import MarkerCluster

width, height = 310,110
popups, locations = []
for idx, row in df.iterrows():
    locations.append([row['STOP_LAT'], row['STOP_LON']])
    name = row['STOPNAME']
    on = row['ON']
    iframe = IFrame(table('Hydroelectric', name, on), width=width, height=height)
    popups.append(iframe)
    
h = folium.FeatureGroup(name='STOPNAME')
h.add_children(MarkerCluster(locations=locations, popups=popups))
mapa.add_children(h)

ValueError: not enough values to unpack (expected 2, got 0)

In [12]:
import folium
map = folium.Map(location=[45.5236, -122.6750])
map.create_map(path='osm.html')

C:\Anaconda\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: Map.create_map is deprecated. Use Map.save instead
  app.launch_new_instance()

In [13]:
import folium
import pandas

map=folium.Map(location=[df['STOP_LAT_13'].mean(),df['STOP_LON_13'].mean()],zoom_start=10,tiles='Mapbox bright')
def color(elev):
    minimum= min(round(df['ON_P_DIFF(INT)']))
    step=(max(round(df['ON_P_DIFF(INT)']))-min(round(df['ON_P_DIFF(INT)'])))/3
    if per in range(minimum,minimum+step):
        col='red'
    elif per in range(minimum+step,minimum+step*2):
        col='orange'
    else:
        col='red'
    return col
fg=folium.FeatureGroup(name="Stops")
for lat,lon,name,per in zip(df['STOP_LAT_13'],df['STOP_LON_13'],df['STOPNAME_13'],round(df['ON_P_DIFF(INT)'])):
    fg.add_child(folium.Marker(location=[lat,lon],popup=(folium.Popup(name)),icon=folium.Icon(color=color(per),icon_color='green')))
map.add_child(fg)

KeyError: 'ON_P_DIFF(INT)'

In [9]:
df.head(25)

,MONTH,DOW,AGENCY_ID,STOP_ID,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,HEADWAY_S,...,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS
0,2009-06-01,1,SFMTA,390,12,12,306,51,277.742329,21.795987,...,1821.331175,1490.383655,0.000000,446.851728,0.000000,0.000000,3260.250000,0.277641,0.019438,6.227592
1,2009-06-01,1,SFMTA,392,12,12,121,17,113.259977,14.226891,...,1031.099350,929.826318,0.000000,161.834352,0.000000,0.581971,1092.000000,0.350798,0.016778,2.320143
2,2009-06-01,1,SFMTA,660,12,12,134,27,136.417078,9.327634,...,5.811606,5.052403,0.000000,1.644894,0.000000,0.280910,2582.416667,0.095128,0.000000,0.000000
3,2009-06-01,1,SFMTA,913,12,8,91,10,78.575469,24.685393,...,98.693709,90.402271,0.685706,56.559066,0.000000,1.000314,984.375000,0.020730,0.000000,0.000000
4,2009-06-01,1,SFMTA,3001,12,11,63,12,63.000000,12.870968,...,43.118121,40.544834,0.000000,4.237888,0.739003,0.000000,882.000000,0.319402,0.015137,1.717830
5,2009-06-01,1,SFMTA,3003,12,11,69,13,69.000000,12.794118,...,79.468817,68.466286,0.000000,39.707940,0.000000,0.427686,927.818182,0.287887,0.061081,2.120921
6,2009-06-01,1,SFMTA,3004,12,11,63,12,63.000000,12.889839,...,23.228131,22.587099,0.000000,70.031518,0.214605,0.000000,882.000000,0.290228,0.015137,0.440342
7,2009-06-01,1,SFMTA,3005,12,11,69,13,69.000000,12.794118,...,34.195059,31.347236,0.000000,37.978882,0.573314,0.000000,927.818182,0.295759,0.061081,4.884898
8,2009-06-01,1,SFMTA,3006,12,11,63,12,63.000000,12.887097,...,53.346130,51.934163,0.000000,76.789849,0.211144,0.000000,882.000000,0.310019,0.015137,0.716132
9,2009-06-01,1,SFMTA,3007,12,11,69,13,69.000000,12.794118,...,166.104371,150.875153,0.000000,94.831415,0.316804,0.000000,922.090909,0.294359,0.061081,3.418075
10,2009-06-01,1,SFMTA,3008,12,11,63,12,63.000000,12.880161,...,135.183645,128.875273,0.000000,82.375681,0.000000,0.000000,882.000000,0.338509,0.026867,3.010786
11,2009-06-01,1,SFMTA,3009,12,11,69,13,69.000000,12.794118,...,102.500952,93.960088,0.000000,62.054662,0.316804,0.000000,922.090909,0.296420,0.061081,4.053149
12,2009-06-01,1,SFMTA,3010,12,11,63,12,63.000000,12.883548,...,76.266857,69.311164,0.000000,56.330371,0.000000,0.000000,882.000000,0.318831,0.015137,1.632499
13,2009-06-01,1,SFMTA,3011,12,11,63,12,63.000000,12.876613,...,289.887087,271.401329,0.000000,69.547491,0.000000,0.000000,882.000000,0.321539,0.015137,0.990721
14,2009-06-01,1,SFMTA,3012,12,12,92,14,81.877595,17.375000,...,124.979635,64.552571,1.823428,180.909833,0.000000,0.862271,962.166667,0.022486,0.000000,0.000000
15,2009-06-01,1,SFMTA,3013,12,11,63,12,63.000000,12.863387,...,506.492153,439.722452,0.000000,107.503146,0.739003,0.751118,882.000000,0.271315,0.003406,0.519559
16,2009-06-01,1,SFMTA,3014,12,11,69,13,69.000000,12.794118,...,102.910616,91.780516,0.000000,50.205690,0.245706,0.000000,927.818182,0.287982,0.061081,4.401500
17,2009-06-01,1,SFMTA,3015,12,11,63,12,63.000000,12.893226,...,45.144646,43.334925,0.000000,63.865939,0.000000,0.000000,876.272727,0.266444,0.015137,0.672749
18,2009-06-01,1,SFMTA,3016,12,8,10,1,9.735397,30.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,118.125000,0.177249,0.000000,0.000000
19,2009-06-01,1,SFMTA,3018,12,11,54,11,54.000000,22.056604,...,324.770009,303.822267,0.000000,67.140182,0.000000,0.000000,801.818182,0.198176,0.000000,0.000000
20,2009-06-01,1,SFMTA,3019,12,12,164,27,153.150290,15.086957,...,4730.103657,4332.952522,0.530388,299.379035,0.000000,0.000000,2244.333333,0.287990,0.021457,6.336528
21,2009-06-01,1,SFMTA,3020,12,11,54,11,54.000000,22.045849,...,73.492827,71.631883,0.000000,17.431402,0.000000,0.000000,801.818182,0.206593,0.000000,0.000000
22,2009-06-01,1,SFMTA,3021,12,11,53,11,54.497611,21.979423,...,129.178645,125.812256,0.000000,21.459395,0.000000,0.000000,790.363636,0.191294,0.000000,0.000000
23,2009-06-01,1,SFMTA,3022,12,8,54,11,54.000000,21.660377,...,83.144988,80.352916,0.000000,16.833956,0.346154,0.000000,1078.875000,0.104506,0.000000,0.000000
24,2009-06-01,1,SFMTA,3023,12,12,91,14,92.528503,22.073596,...,368.087562,254.285352,0.000000,30.675573,0.000000,0.000000,924.000000,0.072879,0.000000,0.000000

Object `replace` not found.

In [ ]:
df['ON_P_DIFF(INT)'].replace

In [101]:
%matplotlib inline

import requests  
import json
from pyproj import Proj
from shapely.geometry import Point
import geopandas as gp

In [109]:
bart = gp.GeoDataFrame.from_file('nybb_15b/nybb.shp')

10