In [1]:
import numpy as np
import pandas as pd
import csv
import bokeh.plotting as bk
import datetime
import os

In [2]:
hdffile = "E:/Transit_Casa/Output/sfmuni_monthly_ts.h5"
store = pd.HDFStore(hdffile)
#df = store.get('rs_tod')

In [3]:
store

<class 'pandas.io.pytables.HDFStore'>
File path: E:/Transit_Casa/Output/sfmuni_monthly_ts.h5
/rs_day                  frame_table  (typ->appendable,nrows->301137,ncols->57,indexers->[index],dc->[MONTH,DOW,AGENCY_ID,ROUTE_SHORT_NAME,DIR,SEQ,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,STOP_ID,ROUTE_LONG_NAME,ROUTE_TYPE,TRIP_HEADSIGN,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS])
/rs_tod                  frame_table  (typ->appendable,nrows->1565864,ncols->58,indexers->[index],dc->[MONTH,DOW,TOD,AGENCY_ID,ROUTE_SHORT_NAME,DIR,SEQ,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,STOP_ID,ROUTE_LONG_NAME,ROUTE_TYPE,TRIP_HEADSIGN,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS])
/stop_day                frame_table  (typ->appendable,nrows->177415,ncols->51,indexers->[index],dc->[MONTH,DOW,AGENCY_ID,STOP_ID,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS])
/stop_tod                frame_table  (typ->appendable,nrows->1125515,ncols->52,indexers->[index],dc->[MONTH,DOW,TOD,AGENCY_ID,STOP_ID,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,HEADWAY_S,FARE,STOPNAME,STOPNAME_AVL,STOP_LAT,STOP_LON,EOL,SOL,TIMEPOINT,ARRIVAL_TIME_DEV,DEPARTURE_TIME_DEV,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,LOAD_ARR,LOAD_DEP,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS])
/system_day_s            frame_table  (typ->appendable,nrows->53,ncols->38,indexers->[index],dc->[MONTH,DOW,AGENCY_ID,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,HEADWAY_S,FARE,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,VC,CROWDED,CROWDHOURS])
/system_tod_s            frame_table  (typ->appendable,nrows->371,ncols->39,indexers->[index],dc->[MONTH,DOW,TOD,AGENCY_ID,NUMDAYS,OBSDAYS,TRIP_STOPS,OBS_TRIP_STOPS,WGT_TRIP_STOPS,HEADWAY_S,FARE,DWELL_S,DWELL,RUNTIME_S,RUNTIME,TOTTIME_S,TOTTIME,SERVMILES_S,SERVMILES,RUNSPEED_S,RUNSPEED,TOTSPEED_S,TOTSPEED,ONTIME5,ON,OFF,PASSMILES,PASSHOURS,WAITHOURS,FULLFARE_REV,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,VC,CROWDED,CROWDHOURS])

In [6]:
df_22 = store.get('rs_tod', where="'ROUTE_SHORT_NAME'='22'")
len(df_22)

TypeError: get() got an unexpected keyword argument 'where'

In [7]:
store.get?

In [10]:
df22 = store.select('rs_tod', where="ROUTE_SHORT_NAME='22'")
len(df22)

34973

In [11]:
df22.head()

,MONTH,DOW,TOD,AGENCY_ID,ROUTE_SHORT_NAME,DIR,SEQ,NUMDAYS,OBSDAYS,TRIP_STOPS,...,PASSDELAY_DEP,PASSDELAY_ARR,RDBRDNGS,DOORCYCLES,WHEELCHAIR,BIKERACK,CAPACITY,VC,CROWDED,CROWDHOURS
857,2009-06-01,1,0300-0559,SFMTA,22,0,1,12,2,2,...,0.0,0.0,0.0,7.539062,0.0,0.0,63.0,0.031746,0.0,0.0
858,2009-06-01,1,0300-0559,SFMTA,22,0,2,12,2,2,...,0.0,0.0,0.0,0.000000,0.0,0.0,63.0,0.103175,0.0,0.0
859,2009-06-01,1,0300-0559,SFMTA,22,0,3,12,2,2,...,0.0,0.0,0.0,0.000000,0.0,0.0,63.0,0.103175,0.0,0.0
860,2009-06-01,1,0300-0559,SFMTA,22,0,4,12,2,2,...,0.0,0.0,0.0,0.000000,0.0,0.0,63.0,0.134921,0.0,0.0
861,2009-06-01,1,0300-0559,SFMTA,22,0,5,12,2,2,...,0.0,0.0,0.0,3.015625,0.0,0.0,63.0,0.126984,0.0,0.0

groups = df22.groupby(by=['MONTH', 'DOW', 'TOD', 'DIR', 'SEQ'])
len(groups)

In [31]:
groups = df22.groupby(by=['DOW', 'TOD', 'DIR', 'SEQ', 'STOP_NAME'])
len(groups)

KeyError: 'STOP_NAME'

In [18]:
groups

In [38]:
agg = df22.groupby(by=['DOW', 'TOD', 'DIR', 'SEQ', 'STOPNAME']).count()
len(agg)

904

In [39]:
table = agg['OBSDAYS'].unstack(level=1)
table.to_csv('missing_months_obs.csv')
table

TOD                                         0300-0559  0600-0859  0900-1359  \
DOW DIR SEQ STOPNAME
1   0   1   Fillmore St & Bay St                 53.0       53.0       53.0
        2   Fillmore St & North Point St         52.0       52.0       52.0
        3   Fillmore St & Beach St               52.0       52.0       52.0
        4   Fillmore St & Jefferson St           52.0       52.0       52.0
        5   Fillmore St & Beach St               52.0       52.0       52.0
        6   Fillmore St & Cervantes Blvd         52.0       52.0       52.0
        7   Fillmore St & Chestnut St            53.0       53.0       53.0
        8   Fillmore St & Lombard St             52.0       52.0       52.0
        9   Union St & Fillmore St               52.0       52.0       52.0
        10  Steiner St & Union St                53.0       53.0       53.0
        11  Steiner St & Green St                52.0       52.0       52.0
        12  Steiner St & Vallejo St              52.0       52.0       52.0
        13  Broadway & Steiner St                52.0       52.0       52.0
        14  Fillmore St & Broadway               52.0       52.0       52.0
        15  Fillmore St & Jackson St              NaN        NaN        NaN
            Jackson St & Fillmore St              NaN        NaN        6.0
        16  Fillmore St & Jackson St             52.0       52.0       52.0
        17  Fillmore St & Sacramento St          52.0       52.0       52.0
        18  Fillmore St & Pine St                52.0       52.0       52.0
        19  Fillmore St & Sutter St              53.0       53.0       53.0
        20  Fillmore St & Geary Blvd             52.0       52.0       52.0
        21  Fillmore St & O'Farrell St           52.0       52.0       52.0
        22  Fillmore St & Eddy St                52.0       52.0       52.0
        23  Fillmore St & Turk St                52.0       52.0       52.0
        24  Fillmore St & Mcallister St          53.0       53.0       53.0
        25  Fillmore St & Grove St               52.0       52.0       52.0
        26  Fillmore St & Hayes St               52.0       52.0       52.0
        27  Fillmore St & Oak St                 52.0       52.0       52.0
        28  Fillmore St & Haight St              53.0       53.0       53.0
        29  Hermann St & Fillmore St             52.0       52.0       52.0
...                                               ...        ...        ...
    1   31  Fillmore St & Geary Blvd             43.0       43.0       43.0
            Fillmore St & O'Farrell St            9.0        9.0        9.0
        32  Fillmore St & Geary Blvd              9.0        9.0        9.0
            Fillmore St & Sutter St              44.0       44.0       44.0
        33  Fillmore St & Pine St                43.0       43.0       43.0
            Fillmore St & Sutter St               9.0        9.0        9.0
        34  Fillmore St & Pine St                 9.0        9.0        9.0
            Fillmore St & Sacramento St          43.0       43.0       43.0
        35  Fillmore St & Jackson St             43.0       43.0       43.0
            Fillmore St & Sacramento St           9.0        9.0        9.0
        36  Fillmore St & Broadway               43.0       43.0       43.0
            Fillmore St & Jackson St              9.0        9.0        9.0
        37  Broadway & Steiner St                43.0       43.0       43.0
            Fillmore St & Broadway                9.0        9.0        9.0
        38  Broadway & Steiner St                 9.0        9.0        9.0
            Steiner St & Vallejo St              43.0       43.0       43.0
        39  Steiner St & Green St                43.0       43.0       43.0
            Steiner St & Vallejo St               9.0        9.0        9.0
        40  Steiner St & Green St                 9.0        9.0        9.0
            Steiner St & Union St                44.0       44.0       44.0
        41  Green St & Steiner St                 NaN        6.0        NaN
            Steiner St & Union St                10.0       10.0       10.0
        42  Fillmore St & Union St               43.0       43.0       43.0
        43  Fillmore St & Lombard St             43.0       43.0       43.0
            Fillmore St & Union St                9.0        9.0        9.0
        44  Fillmore St & Chestnut St            43.0       43.0       43.0
            Fillmore St & Lombard St              9.0        9.0        9.0
        45  Fillmore St & Bay St                 44.0       44.0       44.0
            Fillmore St & Chestnut St             9.0        9.0        9.0
        46  Fillmore St & Bay St                 10.0       10.0       10.0

TOD                                         1400-1559  1600-1859  1900-2159  \
DOW DIR SEQ STOPNAME
1   0   1   Fillmore St & Bay St                 53.0       53.0       53.0
        2   Fillmore St & North Point St         52.0       52.0       52.0
        3   Fillmore St & Beach St               52.0       52.0       52.0
        4   Fillmore St & Jefferson St           52.0       52.0       52.0
        5   Fillmore St & Beach St               52.0       52.0       52.0
        6   Fillmore St & Cervantes Blvd         52.0       52.0       52.0
        7   Fillmore St & Chestnut St            53.0       53.0       53.0
        8   Fillmore St & Lombard St             52.0       52.0       52.0
        9   Union St & Fillmore St               52.0       52.0       52.0
        10  Steiner St & Union St                53.0       53.0       53.0
        11  Steiner St & Green St                52.0       52.0       52.0
        12  Steiner St & Vallejo St              52.0       52.0       52.0
        13  Broadway & Steiner St                52.0       52.0       52.0
        14  Fillmore St & Broadway               52.0       52.0       52.0
        15  Fillmore St & Jackson St              NaN        5.0        5.0
            Jackson St & Fillmore St              NaN       40.0       44.0
        16  Fillmore St & Jackson St             52.0       52.0       52.0
        17  Fillmore St & Sacramento St          52.0       52.0       52.0
        18  Fillmore St & Pine St                52.0       52.0       52.0
        19  Fillmore St & Sutter St              53.0       53.0       53.0
        20  Fillmore St & Geary Blvd             52.0       52.0       52.0
        21  Fillmore St & O'Farrell St           52.0       52.0       52.0
        22  Fillmore St & Eddy St                52.0       52.0       52.0
        23  Fillmore St & Turk St                52.0       52.0       52.0
        24  Fillmore St & Mcallister St          53.0       53.0       53.0
        25  Fillmore St & Grove St               52.0       52.0       52.0
        26  Fillmore St & Hayes St               52.0       52.0       52.0
        27  Fillmore St & Oak St                 52.0       52.0       52.0
        28  Fillmore St & Haight St              53.0       53.0       53.0
        29  Hermann St & Fillmore St             52.0       52.0       52.0
...                                               ...        ...        ...
    1   31  Fillmore St & Geary Blvd             43.0       43.0       43.0
            Fillmore St & O'Farrell St            9.0        9.0        9.0
        32  Fillmore St & Geary Blvd              9.0        9.0        9.0
            Fillmore St & Sutter St              44.0       44.0       44.0
        33  Fillmore St & Pine St                43.0       43.0       43.0
            Fillmore St & Sutter St               9.0        9.0        9.0
        34  Fillmore St & Pine St                 9.0        9.0        9.0
            Fillmore St & Sacramento St          43.0       43.0       43.0
        35  Fillmore St & Jackson St             43.0       43.0       43.0
            Fillmore St & Sacramento St           9.0        9.0        9.0
        36  Fillmore St & Broadway               43.0       43.0       43.0
            Fillmore St & Jackson St              9.0        9.0        9.0
        37  Broadway & Steiner St                43.0       43.0       43.0
            Fillmore St & Broadway                9.0        9.0        9.0
        38  Broadway & Steiner St                 9.0        9.0        9.0
            Steiner St & Vallejo St              43.0       43.0       43.0
        39  Steiner St & Green St                43.0       43.0       43.0
            Steiner St & Vallejo St               9.0        9.0        9.0
        40  Steiner St & Green St                 9.0        9.0        9.0
            Steiner St & Union St                44.0       44.0       44.0
        41  Green St & Steiner St                 NaN        NaN        NaN
            Steiner St & Union St                10.0       10.0       10.0
        42  Fillmore St & Union St               43.0       43.0       43.0
        43  Fillmore St & Lombard St             43.0       43.0       43.0
            Fillmore St & Union St                9.0        9.0        9.0
        44  Fillmore St & Chestnut St            43.0       43.0       43.0
            Fillmore St & Lombard St              9.0        9.0        9.0
        45  Fillmore St & Bay St                 44.0       44.0       44.0
            Fillmore St & Chestnut St             9.0        9.0        9.0
        46  Fillmore St & Bay St                 10.0       10.0       10.0

TOD                                         2200-0259
DOW DIR SEQ STOPNAME
1   0   1   Fillmore St & Bay St                 53.0
        2   Fillmore St & North Point St         52.0
        3   Fillmore St & Beach St               52.0
        4   Fillmore St & Jefferson St           52.0
        5   Fillmore St & Beach St               52.0
        6   Fillmore St & Cervantes Blvd         52.0
        7   Fillmore St & Chestnut St            53.0
        8   Fillmore St & Lombard St             52.0
        9   Union St & Fillmore St               52.0
        10  Steiner St & Union St                53.0
        11  Steiner St & Green St                52.0
        12  Steiner St & Vallejo St              52.0
        13  Broadway & Steiner St                52.0
        14  Fillmore St & Broadway               52.0
        15  Fillmore St & Jackson St              5.0
            Jackson St & Fillmore St             44.0
        16  Fillmore St & Jackson St             52.0
        17  Fillmore St & Sacramento St          52.0
        18  Fillmore St & Pine St                52.0
        19  Fillmore St & Sutter St              53.0
        20  Fillmore St & Geary Blvd             52.0
        21  Fillmore St & O'Farrell St           52.0
        22  Fillmore St & Eddy St                52.0
        23  Fillmore St & Turk St                52.0
        24  Fillmore St & Mcallister St          53.0
        25  Fillmore St & Grove St               52.0
        26  Fillmore St & Hayes St               52.0
        27  Fillmore St & Oak St                 52.0
        28  Fillmore St & Haight St              53.0
        29  Hermann St & Fillmore St             52.0
...                                               ...
    1   31  Fillmore St & Geary Blvd             43.0
            Fillmore St & O'Farrell St            9.0
        32  Fillmore St & Geary Blvd              9.0
            Fillmore St & Sutter St              44.0
        33  Fillmore St & Pine St                43.0
            Fillmore St & Sutter St               9.0
        34  Fillmore St & Pine St                 9.0
            Fillmore St & Sacramento St          43.0
        35  Fillmore St & Jackson St             43.0
            Fillmore St & Sacramento St           9.0
        36  Fillmore St & Broadway               43.0
            Fillmore St & Jackson St              9.0
        37  Broadway & Steiner St                43.0
            Fillmore St & Broadway                9.0
        38  Broadway & Steiner St                 9.0
            Steiner St & Vallejo St              43.0
        39  Steiner St & Green St                43.0
            Steiner St & Vallejo St               9.0
        40  Steiner St & Green St                 9.0
            Steiner St & Union St                44.0
        41  Green St & Steiner St                 NaN
            Steiner St & Union St                10.0
        42  Fillmore St & Union St               43.0
        43  Fillmore St & Lombard St             43.0
            Fillmore St & Union St                9.0
        44  Fillmore St & Chestnut St            43.0
            Fillmore St & Lombard St              9.0
        45  Fillmore St & Bay St                 44.0
            Fillmore St & Chestnut St             9.0
        46  Fillmore St & Bay St                 10.0

[131 rows x 7 columns]