In [1]:
import pandas as pd
pd.set_option('max_rows',500)

In [2]:
tenth = pd.read_csv('E:/Transit-Casa-Share/Data/2010_Split_Buffers_Tenth.csv')

In [3]:
quarter = pd.read_csv('E:/Transit-Casa-Share/Data/2010_Split_Buffers_Quarter.csv')

In [4]:
third = pd.read_csv('E:/Transit-Casa-Share/Data/2010_Split_Buffers_Third.csv')

In [9]:
tenth.head()

,Unnamed: 0,STOP_ID,STOP_LAT,STOP_LON,ALAND10_x,ALAND10_y,AWATER10,BLOCKCE,BLOCKCE10,BLOCKID10,...,AREA_x,AREA_y,AREA,index_right,STOP_ID_2,STOP_LAT_2,STOP_LON_2,geometry,SPLIT_AREA,SPLIT_RATIO
0,0,390,37.72119,-122.475096,185152.052885,17204.0,0.0,1012,1012.0,6.075033e+13,...,4.250499,4.251194,4.250499,0,390,37.72119,-122.475096,"POLYGON ((5990410.094701685 2091617.608273733,...",1.103748,0.259675
1,1,390,37.72119,-122.475096,113483.402269,10544.0,0.0,7011,7011.0,6.075031e+13,...,2.605216,2.605475,2.605216,0,390,37.72119,-122.475096,"POLYGON ((5990497.631667998 2091617.278925879,...",1.877423,0.720640
2,2,390,37.72119,-122.475096,156071.670960,14502.0,0.0,7012,7012.0,6.075031e+13,...,3.582906,3.583517,3.582906,0,390,37.72119,-122.475096,"POLYGON ((5990670.887957375 2091570.737487555,...",2.054472,0.573409
3,3,390,37.72119,-122.475096,69035.569756,6415.0,0.0,1001,1001.0,6.075033e+13,...,1.584836,1.585179,1.584836,0,390,37.72119,-122.475096,"POLYGON ((5989942.805526927 2090948.068907045,...",0.859399,0.542264
4,4,390,37.72119,-122.475096,22805.829990,2119.0,0.0,1017,1017.0,6.075033e+13,...,0.523549,0.523615,0.523549,0,390,37.72119,-122.475096,"POLYGON ((5990138.526319418 2090935.019779101,...",0.148640,0.283909

In [10]:
quarter.head()

,Unnamed: 0,STOP_ID,STOP_LAT,STOP_LON,ALAND10_x,ALAND10_y,AWATER10,BLOCKCE,BLOCKCE10,BLOCKID10,...,AREA_x,AREA_y,AREA,index_right,STOP_ID_2,STOP_LAT_2,STOP_LON_2,geometry,SPLIT_AREA,SPLIT_RATIO
0,0,390,37.72119,-122.475096,113483.402269,10544.0,0.0,7011,7011.0,6.075031e+13,...,2.605216,2.605475,2.605216,0,390,37.72119,-122.475096,"POLYGON ((5990694.091354781 2091763.135185194,...",2.605216,1.000000
1,1,390,37.72119,-122.475096,156071.670960,14502.0,0.0,7012,7012.0,6.075031e+13,...,3.582906,3.583517,3.582906,0,390,37.72119,-122.475096,"POLYGON ((5990676.315123574 2091606.176268263,...",3.582906,1.000000
2,2,390,37.72119,-122.475096,144381.489796,13415.0,0.0,7007,7007.0,6.075031e+13,...,3.314537,3.314914,3.314537,0,390,37.72119,-122.475096,"POLYGON ((5990907.781641605 2091484.385444446,...",3.314537,1.000000
3,3,390,37.72119,-122.475096,117418.326151,10910.0,0.0,7009,7009.0,6.075031e+13,...,2.695549,2.695916,2.695549,0,390,37.72119,-122.475096,"POLYGON ((5990948.344178248 2091747.938406161,...",2.694899,0.999759
4,4,390,37.72119,-122.475096,160808.956576,14942.0,0.0,7008,7008.0,6.075031e+13,...,3.691659,3.692243,3.691659,0,390,37.72119,-122.475096,"POLYGON ((5991197.963010494 2091732.47751007, ...",2.925484,0.792458

In [11]:
third.head()

,Unnamed: 0,STOP_ID,STOP_LAT,STOP_LON,ALAND10_x,ALAND10_y,AWATER10,BLOCKCE,BLOCKCE10,BLOCKID10,...,AREA_x,AREA_y,AREA,index_right,STOP_ID_2,STOP_LAT_2,STOP_LON_2,geometry,SPLIT_AREA,SPLIT_RATIO
0,0,390,37.72119,-122.475096,1.155658e+05,10738.0,0.0,1014,1014.0,6.075033e+13,...,2.653020,2.653413,2.653020,0,390,37.72119,-122.475096,"POLYGON ((5988717.087440591 2091386.133750314,...",1.206511,0.454769
1,1,390,37.72119,-122.475096,5.019060e+06,466354.0,0.0,1005,1005.0,6.075033e+13,...,115.221546,115.238405,115.221546,0,390,37.72119,-122.475096,"POLYGON ((5988857.332677396 2091377.295516922,...",55.813508,0.484402
2,2,390,37.72119,-122.475096,5.419756e+05,50359.0,0.0,1006,1006.0,6.075033e+13,...,12.442026,12.443961,12.442026,0,390,37.72119,-122.475096,"POLYGON ((5990010.299511184 2092793.515439182,...",0.643771,0.051742
3,3,390,37.72119,-122.475096,1.292767e+05,12012.0,0.0,1007,1007.0,6.075033e+13,...,2.967780,2.968225,2.967780,0,390,37.72119,-122.475096,"POLYGON ((5990201.762849662 2092831.809938113,...",0.815858,0.274905
4,4,390,37.72119,-122.475096,1.851521e+05,17204.0,0.0,1012,1012.0,6.075033e+13,...,4.250499,4.251194,4.250499,0,390,37.72119,-122.475096,"POLYGON ((5990489.01033121 2092849.702373355, ...",3.577057,0.841562

71523.214370778238

In [5]:
# for a tenth mile radius the buffers should be 20.1 acres and there are 3,563 buffers
# meaning the total area should be 71,602 acres
# percent diff is 0.48%

area10 =  tenth[['SPLIT_AREA','STOP_ID']].groupby(by = 'STOP_ID').sum()
print(area10.head())
area10['SPLIT_AREA'] = area10.SPLIT_AREA.astype(int)
print('Buffer size = ' + str(area10.SPLIT_AREA.unique()))
sum(area10.SPLIT_AREA)

         SPLIT_AREA
STOP_ID
390       20.073874
392       20.073874
660       20.073874
913       20.073874
3001      20.073874
Buffer size = [20]

71260

In [6]:
# for a quarter mile radius the buffers should be 125.6 acres and there are 3,563 buffers
# meaning the total area should be 447,512 acres 
# percent diff is 0.4%
    
area4 =  quarter[['SPLIT_AREA','STOP_ID']].groupby(by = 'STOP_ID').sum()
print(area4.head())
area4['SPLIT_AREA'] = area4.SPLIT_AREA.astype(int)
print('Buffer size = ' + str(area4.SPLIT_AREA.unique()))
sum(area4.SPLIT_AREA)

         SPLIT_AREA
STOP_ID
390      125.461715
392      125.461715
660      125.461715
913      125.461715
3001     125.461715
Buffer size = [125]

445375

In [7]:
# for a quarter mile radius the buffers should be 223.3 acres and there are 3,563 buffers
# meaning the total area should be 795,577 acres 
# percent diff is 0.11%
    
area3 =  third[['SPLIT_AREA','STOP_ID']].groupby(by = 'STOP_ID').sum()
print(area3.head())
area4['SPLIT_AREA'] = area4.SPLIT_AREA.astype(int)
print('Buffer size = ' + str(area3.SPLIT_AREA.unique()))
sum(area3.SPLIT_AREA)

         SPLIT_AREA
STOP_ID
390      223.043049
392      223.043049
660      223.043049
913      223.043047
3001     223.043049
Buffer size = [ 223.04304874  223.04304854  223.04304879 ...,  223.04304748  223.04305064
  223.0430495 ]

794702.38194808713

In [8]:
len(tenth.STOP_ID.unique())

3563